- hosts: all
  connection: local
  gather_facts: no

  tasks:
  - name: configure an ipv4 host record
    nios_host_record:
      name: "{{ host_name }}"
      ipv4:
        - address: "{{ ip_address }}"
      state: present
      provider:
        host: "192.168.1.155"
        username: admin
        password: admin