---
- hosts: all
  gather_facts: false

  tasks:
    - name: Gather only the interfaces resource facts and no legacy facts
      nxos_facts:
        gather_subset:
          - '!all'
          - '!min'
        gather_network_resources:
          - interfaces