- hosts: all
  gather_facts: no
  connection: local
  environment:
    PYTHONHTTPSVERIFY: 0

  tasks:
    - name: show list of all interfaces
      panos_op:
        ip_address: '{{ inventory_hostname }}'
        username: 'admin'
        password: 'admin'
        cmd: 'show interfaces all'
