- hosts: all
  gather_facts: no
  connection: local
  environment:
    PYTHONHTTPSVERIFY: 0

  tasks:
    - name: setup security profile group
      panos_pg:
        ip_address: "192.168.1.70"
        password: "admin"
        username: "admin"
        pg_name: "pg-default"
