---
- hosts: all
  connection: network_cli
  gather_facts: no
  

  tasks:
    - name: configure interface
      ios_interface:
        name: GigabitEthernet0/2
        description: test-interface
        speed: 100
        duplex: half
        mtu: 512