---
- hosts: all
  connection: network_cli
  gather_facts: no
  
  tasks:
    - name: Admin down an interface
      nxos_interface:
        name: Ethernet0/4
        admin_state: down
      connection: httpapi