---
- name: pulling ntp servers on device
  ios_command:
    commands: show run | i ntp
  register: output

- name: look at output
  debug:
    var: output.stdout_lines

- name: compare ntp servers and remove erroroneous entries
  ios_config:
    lines: no {{ item }}
  loop: "{{ output.stdout_lines[0] }}"
  when: item not in ntp_servers


- name: add ntp servers
  ios_config:
    lines: "{{ item }}"
  loop: "{{ ntp_servers }}"

- name: configure the motd banner
  ios_banner:
    banner: motd
    text: |
      this is my motd banner
      that contains a multiline
      string
    state: present
