---
- name: configure interface
  ios_interface:
    name: "{{ item.interface }}"
    description: "{{ item.description }}"
    enabled: True
    provider:
      authorize: no
  with_items: "{{ l2_interfaces }}"

- name: configure name servers
  ios_system:
    name_servers: "{{ item.servers }}"
  with_items: "{{ name_servers }}"

- name: configure ntp servers
  ios_config:
    lines:
      - ntp server {{ item.ntp }}
    provider:
      authorize: no
  with_items: "{{ ntp_servers }}"

- name: show vlans
  ios_command:
    commands: show vlan
  register: vlans

- name: Add interfaces to VLAN
  ios_vlan:
    vlan_id: "{{ item.vlan}}"
    interfaces: "{{ item.interfaces }}"
  with_items: "{{ vlan_id }}"
  when: vlans
