---
- name: BACKUP THE CONFIG
  ios_config:
    backup: yes
  register: config_output

- name: RENAME BACKUP
  copy:
    src: "{{config_output.backup_path}}"
    dest: "./backup/{{inventory_hostname}}.config"

- name: REMOVE NON CONFIG LINES
  lineinfile:
    path: "{{playbook_dir}}/backup/{{inventory_hostname}}.config"
    line: "Building configuration..."
    state: absent

- name: REMOVE NON CONFIG LINES - REGEXP
  lineinfile:
    path: "{{playbook_dir}}/backup/{{inventory_hostname}}.config"
    regexp: 'Current configuration.*'
    state: absent

- name: REMOVE NON CONFIG LINES - REGEXP
  lineinfile:
    path: "{{playbook_dir}}/backup/{{inventory_hostname}}.config"
    regexp: '!Command.*'
    state: absent

- name: REMOVE NON CONFIG LINES - REGEXP
  lineinfile:
    path: "{{playbook_dir}}/backup/{{inventory_hostname}}.config"
    regexp: '!Running.*'
    state: absent

- name: REMOVE NON CONFIG LINES - REGEXP
  lineinfile:
    path: "{{playbook_dir}}/backup/{{inventory_hostname}}.config"
    regexp: '!Time.*'
    state: absent

- name: REMOVE NON CONFIG LINES - REGEXP
  lineinfile:
    path: "{{playbook_dir}}/backup/{{inventory_hostname}}.config"
    regexp: 'version.+'
    state: absent